#!/usr/bin/env python3
"""Export a fold-specific target-user OnlineLayer head as Rust constants."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def fmt_f32(value: float) -> str:
    return f"{value:.9g}_f32"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target-user", type=int, required=True)
    parser.add_argument(
        "--head-json",
        type=Path,
        default=None,
        help="Path to microflow32_user<N>_head_float.json.",
    )
    parser.add_argument(
        "--out-rs",
        type=Path,
        default=None,
        help="Output Rust file under src/eval_artifacts by default.",
    )
    args = parser.parse_args()

    head_json = args.head_json or (
        PROJECT_ROOT
        / "results"
        / "fold_artifacts"
        / f"wisdm_user{args.target_user}_microflow32"
        / f"microflow32_user{args.target_user}_head_float.json"
    )
    out_rs = args.out_rs or (
        PROJECT_ROOT / "src" / "eval_artifacts" / f"wisdm_user{args.target_user}_head.rs"
    )

    payload = json.loads(head_json.read_text(encoding="utf-8"))
    weights = payload["weights"]
    bias = payload["bias"]
    feature_dim = int(payload["feature_dim"])
    num_classes = int(payload["num_classes"])

    lines: list[str] = []
    lines.append("// Generated by scripts/data/export_wisdm_target_user_head_rust.py.")
    lines.append("// Fold-specific OnlineLayer32 head. Do not edit by hand.")
    lines.append("")
    lines.append(
        "pub const WISDM_USER_HEAD_WEIGHTS: [[f32; NUM_CLASSES]; "
        "MICROFLOW32_FEATURE_TENSOR_SIZE] = ["
    )
    for row in weights:
        lines.append("    [")
        for value in row:
            lines.append(f"        {fmt_f32(float(value))},")
        lines.append("    ],")
    lines.append("];")
    lines.append("")
    lines.append("pub const WISDM_USER_HEAD_BIAS: [f32; NUM_CLASSES] = [")
    for value in bias:
        lines.append(f"    {fmt_f32(float(value))},")
    lines.append("];")
    lines.append("")
    lines.append(f"pub const WISDM_USER_HEAD_FEATURE_DIM: usize = {feature_dim};")
    lines.append(f"pub const WISDM_USER_HEAD_NUM_CLASSES: usize = {num_classes};")

    out_rs.parent.mkdir(parents=True, exist_ok=True)
    out_rs.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_rs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
